name: GitHub-Profile-3D-Contrib
# Generates multiple styles of 3D GitHub contribution charts
# and updates README automatically.

on:
  schedule:
    - cron: "0 10 * * *"  # Every day at 10:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate 3D Contribution Charts (Main Style)
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      # Repeat for additional styles if you want variations
      # Each run overwrites `profile-3d-contrib` with the selected style
      - name: Generate Night View
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: ./sample-settings/night.json

      - name: Optimize SVG files
        run: |
          sudo apt-get update && sudo apt-get install -y svgo
          svgo -f profile-3d-contrib --multipass

      - name: Update README with latest chart
        run: |
          # Replace placeholder in README.md with new image link
          sed -i 's|!\[3D GitHub Profile\](.*)|![3D GitHub Profile](./profile-3d-contrib/profile-green-animate.svg)|' README.md

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "🖼 Update GitHub 3D Contribution Charts ($(date +'%Y-%m-%d %H:%M:%S'))" || echo "No changes to commit"
          git push

      - name: Show Summary
        run: |
          echo "✅ 3D Contribution Charts Updated!" >> $GITHUB_STEP_SUMMARY
          echo "📅 Run Time: $(date)" >> $GITHUB_STEP_SUMMARY
